[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 115200

lib_deps =
    bodmer/TFT_eSPI
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson
    chris--a/Keypad

build_flags =
    -D USER_SETUP_LOADED
    -D ILI9341_2_DRIVER
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=16
    -D TFT_RST=17
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8
    -D SPI_FREQUENCY=27000000